// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBukCVR8AjPU15ZZWshoSLINgKMlP3LU-M',
    appId: '1:391872355874:web:1365c94e1ece97a127347b',
    messagingSenderId: '391872355874',
    projectId: 'fastcure',
    authDomain: 'fastcure.firebaseapp.com',
    storageBucket: 'fastcure.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhOerChjmWkJzWM8pAbKxH6tbkCStCutE',
    appId: '1:391872355874:android:aa1023e0aa934af527347b',
    messagingSenderId: '391872355874',
    projectId: 'fastcure',
    storageBucket: 'fastcure.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzLEFZx6WrXyrc99gNReWMKIxNhezhrTE',
    appId: '1:391872355874:ios:2945bb5337dc269227347b',
    messagingSenderId: '391872355874',
    projectId: 'fastcure',
    storageBucket: 'fastcure.firebasestorage.app',
    iosBundleId: 'com.fastcure.fastcure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzLEFZx6WrXyrc99gNReWMKIxNhezhrTE',
    appId: '1:391872355874:ios:2945bb5337dc269227347b',
    messagingSenderId: '391872355874',
    projectId: 'fastcure',
    storageBucket: 'fastcure.firebasestorage.app',
    iosBundleId: 'com.fastcure.fastcure',
  );
}
